### ISSUE TITLE
mDNS Responder 

### ISSUE THREAD

**Issue by mqshaw** [Xylopyrographer/STAC#36]
When setting up the STAC for the first time we have to remember the custom IP Address for the STAC once connected to the WiFi access point.
   http://192.168.6.14

Instead, what about using an mDNS responder to use a simple, easy to remember hostname for the STAC such as 
   http://stac.local/

Here is an example tutorial that we can use as a baseline.
   https://techtutorialsx.com/2020/04/17/esp32-mdns-address-resolution/

**Comment by Xylopyrographer** [comment]
Super idea!

**Comment by Xylopyrographer** [comment]
With that, might also be able in include OTA firmware updates. Which would be cool.

Here's the sketch I used to test OTA for the STAC. (Had to add the .txt extension to keep GitHub happy 🙄.)

[AtomOTAWebUpdater.ino.txt](https://github.com/Xylopyrographer/STAC/files/6549660/AtomOTAWebUpdater.ino.txt)

**Comment by mqshaw** [comment]
Sounds great, i will mock up a protoype and we can go from there.

Mark


Sent from my mobile device. Please forgive gross autocorrect failures or grammatical errors.

________________________________

**Comment by mqshaw** [comment]
Your example code looks great.

**Comment by Xylopyrographer** [comment]
Thanks. Was kind of anti-climatic when I ran it. It just...worked 😄!

Agree that working through the various libraries and feature set of each will take a bit of noodling. We definitely want only one connection at a time to the STAC.

I've got a few things going on between now and mid next week. I can start to poke around after that.

Something else for you. I'm monitoring the arduino-esp32 Issues on GitHub. A thread came up about the log_X() functions. A person there noted:
"you can toggle core logging off/on (IF ITS compiled in !) using: 

`Serial.setDebugOutput(true | false);`"

Haven't tested that to know if they meant "turn off the entire log_X() functionality" or "turn off just the log_X() stuff that originates in the libraries" or if you can turn it off in one part of the code and then turn it back on in another...

Regardless, might be of use if you're running a debug version at service tomorrow.

**Comment by mqshaw** [comment]
I posted the log from my debug trace on Sunday night here #35.

**Comment by Xylopyrographer** [comment]
Implemented in version 2.1 👍
